import type { Metadata } from "next";
import NavBar from "@/components/layout/NavBar";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import { Maven_Pro, Barriecito } from "next/font/google";

const mavenPro = Maven_Pro({
  weight: "variable",
  subsets: ["latin"],
  variable: "--font-maven-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const barraecito = Barriecito({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-barriecito",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" className={(mavenPro.variable, barraecito.variable)}>
      <body>
        <div className="flex min-h-screen flex-col">
          <NavBar />
          <main className="flex flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
