// import type { Metadata } from "next";
import NavBar from "@/components/ui/layout/NavBar";
import "./globals.css";
import Footer from "@/components/ui/layout/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
